### ISSUE TITLE
Disable cheats & savestates in Mupen64Plus

### ISSUE THREAD

**Issue by Henrik0x7F** [net64-mod/net64-coop#14]

**Comment by fancythedeveloper** [comment]
Why this tho? Cheats and savestates were useful in SM64O 1.X-Net64+ 2.X.

**Comment by Henrik0x7F** [comment]
Savestates will break the communication between client and game.

**Comment by Henrik0x7F** [comment]
Well, maybe it is possible to allow them for offline play only. I don't know. It's to early to be sure.
