### ISSUE TITLE
Cannot join/create server

### ISSUE THREAD

**Issue by Jujuyeh** [net64-mod/net64-coop#63]
**Describe the bug**  
I'm not 100% sure about what's the issue but it seems that when clicking on "Join" server, it actually creates a local one. And I said I'm not 100% sure because of that, I cannot confirm either that it creates a new server properly. Messages won't send on the chat, I can only "Stop" the server.

Mupen64plus launches just fine. I've tried with a friend (same OS) with no luck using a VPN.

**To Reproduce**  
Join or create a new server. Both seem to create a new *dummy* server. I had properly set a name and a vanilla US ROM. Emulator plugins are mupen64plus defaults.

**Expected behavior**  
Join or host a game.

**Logs, screenshots or video captures**  
![image](https://user-images.githubusercontent.com/13997685/79697442-2c132400-8283-11ea-91df-84314496ddfd.png)

![image](https://user-images.githubusercontent.com/13997685/79697463-4baa4c80-8283-11ea-9758-cda99097b438.png)

```
[info] [frontend] Starting Net64 332ee1f-dirty
[info] [frontend] Operating system: arch unknown
[info] [frontend] Kernel: linux 5.6.3-arch1-1
[info] [frontend] CPU architecture: buildtime=x86_64 runtime=x86_64
[info] [frontend] Byte order: Little
[info] [frontend] Configuration folder: "/home/user/.local/share/Net64 Project/Net64"
QMetaObject::connectSlotsByName: No matching signal for on_emulator_settings()
QMetaObject::connectSlotsByName: No matching signal for on_start_server_btn_pressed()
QMetaObject::connectSlotsByName: No matching signal for on_connect_btn_pressed()
QMetaObject::connectSlotsByName: No matching signal for on_disconnect_btn_pressed()
QMetaObject::connectSlotsByName: No matching signal for on_stop_server_btn_pressed()
QMetaObject::connectSlotsByName: No matching signal for on_emulator_state(Net64::Emulator::State)
QMetaObject::connectSlotsByName: No matching signal for on_emulator_started()
QMetaObject::connectSlotsByName: No matching signal for on_emulator_paused()
QMetaObject::connectSlotsByName: No matching signal for on_emulator_unpaused()
QMetaObject::connectSlotsByName: No matching signal for on_emulator_joinable()
[info] [mupen64plus] Initialized Mupen64Plus Core v132352, api: 0x20101 (capabilities: 0x1)
[info] [mupen64plus] Initialized VIDEO plugin Mupen64Plus OpenGL Video Plugin by Rice v132352, api: 0x20200 (capabilities: 0x0)
[info] [mupen64plus] Initialized AUDIO plugin Mupen64Plus SDL Audio Plugin v132352, api: 0x20000 (capabilities: 0x0)
[info] [mupen64plus] Initialized RSP plugin Hacktarux/Azimer High-Level Emulation RSP Plugin v132352, api: 0x20000 (capabilities: 0x0)
[info] [mupen64plus] Initialized INPUT plugin Mupen64Plus SDL Input Plugin v132352, api: 0x20000 (capabilities: 0x0)
[info] [mupen64plus] Starting n64 emulation
[info] [mupen64plus] Started n64 emulation
```

**Environment (please complete the following information):**
 - OS: Arch Linux (19 April 2020)
 - Emulator: mupen64plus 2.5.0
 - Net64 Version: 332ee1f-dirty

**Comment by Henrik0x7F** [comment]
This repository is work in progress. If you intend to actually play sm64 online then you should head to https://github.com/Tarnadas/net64plus/

Eventually this version here will become playable and replace / supplement the one mentioned above. I'm sorry if this wasn't clear. In case you still have issues setting up it might be a good idea to ask on our discord server as there are many people experienced with that version.
